version: 0.1
log:
  fields:
    service: registry
storage:
  s3:
    accesskey: #AWS_KEY#
    secretkey: #AWS_SECRET#
    region: #AWS_REGION#
    bucket: #AWS_BUCKET#
    rootdirectory: #STORAGE_PATH#
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
